### ISSUE TITLE
Charts duplicate labels

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#93] opened 2023-12-05 19:37 UTC
![41E4C3DE-B240-4F02-AE25-9D39DEF6A205](https://github.com/brittanyarima/Steps/assets/76922883/5818276d-1d22-4977-8972-4b8bb3d7ab6f)

**Comment by in60dev** [comment] 2024-01-28 00:20
Hey,

I found something about this bug.

It's not only a duplicate of the label, it's a stacking of the bars and the labels.
Each time the NewWeekStepsView appears, the bars are stacked. 

<img width="367" alt="Bildschirmfoto 2024-01-28 um 01 19 32" src="https://github.com/brittanyarima/Steps/assets/50228790/81195047-fb78-4829-b2ef-3f81e0e3c4f8">

<img width="366" alt="Bildschirmfoto 2024-01-28 um 00 49 53" src="https://github.com/brittanyarima/Steps/assets/50228790/7f298c8a-6307-40d2-97fa-80d49a1c589e">

Observe the daily goal  line of 10,000 steps.


What else I noticed: The file NewWeekStepsView.swift has two times a reference in the project navigator.

<img width="247" alt="Bildschirmfoto 2024-01-28 um 00 54 28" src="https://github.com/brittanyarima/Steps/assets/50228790/25851fcd-59c3-412f-80bb-8e769a757ad1">

Removing the reference and adding the file again did not fix the problem.

I am a Swift and SwiftUI beginner and have not found a solution. 😔
I hope this information can help someone fix this error.

I would be pleased to receive a message with the solution when it has been found.

~Ingo

**Comment by brittanyarima** [comment] 2024-01-31 22:57
@in60dev thanks for sharing this! Definitely will help solving this error!

**Comment by kritiagarwal13** [comment] 2024-01-31 23:22
I can take a look at this one.

**Comment by brittanyarima** [comment] 2024-02-01 21:01
@kritiagarwal13 thank you! Just assigned you

**Closed as completed** 2024-02-04 04:24 UTC
Labels: bug, help wanted, priority
